# Организация
org.gradle.jvmargs=-Xmx4G -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true

# Kotlin
kotlin.code.style=official

# Android
android.useAndroidX=true
android.enableJetifier=true

# Оптимизация сборки
android.enableR8.fullMode=true

# Решение проблем с Kotlin daemon на Windows
# Если у вас проблемы с длинными путями на Windows, раскомментируйте:
# kotlin.daemon.useFallbackStrategy=true
# kotlin.compiler.execution.strategy=in-process